name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Add these permissions
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Update to v4

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Update to v3
        with:
          node-version: "20.12.1"
          cache: "npm" # Add caching

      - name: Install Dependencies
        run: npm ci # Use ci instead of install for cleaner installs

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4 # Update to v4
        with:
          branch: gh-pages
          folder: dist
          clean: true # Add this to clean up old files
