export const COURSES_TO_METADATA = {
  bigData: {name:"Big Data", cost: 1000, hoursToComplete: 10 },
  customerExperience1: {name:"Customer Experience 1", cost: 1000, hoursToComplete: 10 },
  customerExperience2: {name:"Customer Experience 2", cost: 1000, hoursToComplete: 10 },
  designThinking: {name:"Design Thinking", cost: 1000, hoursToComplete: 10 },
  digitalMarketing: {name:"Digital Marketing", cost: 1000, hoursToComplete: 10 },
  engineeringLeadership: {name:"Engineering Leadership", cost: 1000, hoursToComplete: 10 },
  executiveEducationAdvisorTraining: {name:"Executive Education Advisor Training", cost: 1000, hoursToComplete: 10 },
  generateAiAndValuation: {name:"Generative AI & Valuation", cost: 1000, hoursToComplete: 10 },
  greenTechnologiesAndAi: {name:"Green Technologies and AI", cost: 1000, hoursToComplete: 10 },
  instructorCertificateProgram: {name:"Instructor Certificate Program", cost: 1000, hoursToComplete: 10 },
  itCybersecurityLeadershipTeams: {name:"IT & Cybersecurity Leadership Teams", cost: 1000, hoursToComplete: 10 },
  mentorCertificateProgram: {name:"Mentor Certificate Program", cost: 1000, hoursToComplete: 10 },
  strategicAi: {name:"Strategic AI", cost: 1000, hoursToComplete: 10 },
  strategicAiForHealthcareProfessionals: {name: "Strategic AI for Healthcare Professionals",
    cost: 1000,
    hoursToComplete: 10,
  },
  strategicAiForHrProfessionals: {name: "Strategic AI for HR Professionals", cost: 1000, hoursToComplete: 10 },
  strategicAiInSales: {name: "Strategic AI in Sales", cost: 1000, hoursToComplete: 10 },
  transformationLeadership: {name: "Transformation Leadership", cost: 1000, hoursToComplete: 10 },
  womenInLeadership: {name: "Women in Leadership", cost: 1000, hoursToComplete: 10 },
};

export const INDUSTRIES_TO_METADATA = {
  advertisingAndMarketing: {name: "Advertising and Marketing", averageHourlyWage: 10 },
  aerospace: {name: "Aerospace", averageHourlyWage: 10 },
  agriculture: {name: "Agriculture", averageHourlyWage: 10 },
  computerAndTechnology: {name: "Computer and Technology", averageHourlyWage: 10 },
  construction: {name: "Construction", averageHourlyWage: 10 },
  education: {name: "Education", averageHourlyWage: 10 },
  energy: {name: "Energy", averageHourlyWage: 10 },
  entertainment: {name: "Entertainment", averageHourlyWage: 10 },
  fashion: {name: "Fashion", averageHourlyWage: 10 },
  financeAndEconomic: {name: "Finance and Economic", averageHourlyWage: 10 },
  foodAndBeverage: {name: "Food and Beverage", averageHourlyWage: 10 },
  healthcare: {name: "Healthcare", averageHourlyWage: 10 },
  hospitality: {name: "Hospitality", averageHourlyWage: 10 },
  manufacturing: {name: "Manufacturing", averageHourlyWage: 10 },
  mediaAndNews: {name: "Media and News", averageHourlyWage: 10 },
  mining: {name: "Mining", averageHourlyWage: 10 },
  pharmaceutical: {name: "Pharmaceutical", averageHourlyWage: 10 },
  telecommunication: {name: "Telecommunication", averageHourlyWage: 10 },
  transportation: {name: "Transportation", averageHourlyWage: 10 },
};
